import type { Metadata } from "next";
import { Amarante, Didact_Gothic, Rubik_80s_Fade } from "next/font/google";
import "./globals.css";

const poppins = Didact_Gothic({
  weight: "400",
  variable: "--font-poppins",
  subsets: ["latin"],
});
const amarante = Amarante({
  weight: "400",
  variable: "--font-amarante",
  subsets: ["latin"],
});
const rubik = Rubik_80s_Fade({
  weight: "400",
  variable: "--font-rubik",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Ramel Panis | Product Designer & front end developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${amarante.variable}  ${rubik.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
